USE [master]
GO
/****** Object:  Database [DB_CLIENTES_DERL]    Script Date: 6/12/2023 20:21:22 ******/
CREATE DATABASE [DB_CLIENTES_DERL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_CLIENTES_DERL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DB_CLIENTES_DERL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_CLIENTES_DERL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DB_CLIENTES_DERL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_CLIENTES_DERL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET ARITHABORT OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET  MULTI_USER 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET QUERY_STORE = ON
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [DB_CLIENTES_DERL]
GO
/****** Object:  User [USUARIO]    Script Date: 6/12/2023 20:21:22 ******/
CREATE USER [USUARIO] FOR LOGIN [usuario] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 6/12/2023 20:21:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cliente]    Script Date: 6/12/2023 20:21:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cliente](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Paterno] [varchar](30) NULL,
	[Materno] [varchar](30) NULL,
	[Nombres] [varchar](30) NULL,
	[CI] [char](12) NULL,
	[FechaNacimiento] [datetime] NULL,
	[Genero] [varchar](30) NULL,
	[Celular] [int] NULL,
	[NivelIngresos] [decimal](18, 2) NULL,
	[Correo] [varchar](30) NULL,
	[Cuenta] [varchar](14) NULL,
	[FechaRegistro] [datetime] NULL,
	[FechaActualizacion] [datetime] NULL,
 CONSTRAINT [PK_Cliente_1] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Clientes]    Script Date: 6/12/2023 20:21:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clientes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Paterno] [nvarchar](max) NOT NULL,
	[Materno] [nvarchar](max) NOT NULL,
	[Nombres] [nvarchar](max) NOT NULL,
	[CI] [nvarchar](max) NOT NULL,
	[FechaNacimiento] [datetime2](7) NOT NULL,
	[Genero] [nvarchar](max) NOT NULL,
	[Celular] [int] NOT NULL,
	[NivelIngresos] [decimal](18, 2) NOT NULL,
	[Correo] [nvarchar](max) NOT NULL,
	[Cuenta] [nvarchar](max) NOT NULL,
	[FechaRegistro] [datetime2](7) NOT NULL,
	[FechaActualizacion] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Clientes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cuenta]    Script Date: 6/12/2023 20:21:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cuenta](
	[Id] [int] NOT NULL,
	[TipoCuenta] [varchar](30) NULL,
	[FechaCreacion] [datetime] NULL,
	[FechaActualizacion] [datetime] NULL,
	[Saldo] [decimal](18, 2) NULL,
	[ClienteId] [int] NULL,
 CONSTRAINT [PK_Cuenta] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cuentas]    Script Date: 6/12/2023 20:21:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cuentas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Saldo] [decimal](18, 2) NOT NULL,
	[FechaCreacion] [datetime2](7) NOT NULL,
	[FechaActualizacion] [datetime2](7) NOT NULL,
	[TipoCuenta] [nvarchar](max) NOT NULL,
	[ClienteId] [int] NOT NULL,
 CONSTRAINT [PK_Cuentas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20231206215604_Initial', N'8.0.0')
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20231206220245_Initial1', N'8.0.0')
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20231206235547_Initial2', N'8.0.0')
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20231206235734_Initial3', N'8.0.0')
GO
SET IDENTITY_INSERT [dbo].[Cliente] ON 
GO
INSERT [dbo].[Cliente] ([Id], [Paterno], [Materno], [Nombres], [CI], [FechaNacimiento], [Genero], [Celular], [NivelIngresos], [Correo], [Cuenta], [FechaRegistro], [FechaActualizacion]) VALUES (1, N'Rios', NULL, NULL, N'8461660     ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
SET IDENTITY_INSERT [dbo].[Cliente] OFF
GO
ALTER TABLE [dbo].[Cuenta]  WITH CHECK ADD  CONSTRAINT [FK_Cuenta_Cuenta] FOREIGN KEY([Id])
REFERENCES [dbo].[Cuenta] ([Id])
GO
ALTER TABLE [dbo].[Cuenta] CHECK CONSTRAINT [FK_Cuenta_Cuenta]
GO
USE [master]
GO
ALTER DATABASE [DB_CLIENTES_DERL] SET  READ_WRITE 
GO
